### ISSUE TITLE
Set up an RSS feed for The Weekly Backdrop.

### ISSUE THREAD

**Issue by serundeputy** [aturnintime/howtobackdrop.com#4]

**Comment by BWPanda** [comment]
Here's a PR: https://github.com/aturnintime/howtobackdrop.com/pull/6

Hope I did it right... Couldn't test it as I didn't have access to the DB so was having errors and issues all over the place, but was able to setup the view at least, so hope it gives a start if nothing else :slightly_smiling_face:

**Comment by serundeputy** [comment]
You are amazing! Let me get you a DB dump.

**Comment by BWPanda** [comment]
Yep, works: 

![image](https://user-images.githubusercontent.com/2385329/76025525-ca4a6500-5f35-11ea-8555-d5f3d7c27831.png)

Seems to be missing some styling though (e.g. News heading). Couldn't work out why (my personal blog's RSS feed has styles included). But I think fine as-is, considering the site is minimally styled anyway.

**Comment by serundeputy** [comment]
cool thanks! I'll get this merged/deployed soon.
